INSERT INTO Collections VALUES(1,'wt','2014-05-01')
INSERT INTO Collections VALUES(2,'wt','2015-05-01')
INSERT INTO Collections VALUES(1,'wyh','2013-05-15')
INSERT INTO Collections VALUES(2,'wyh','2015-05-20')
INSERT INTO Collections VALUES(3,'wyh','2016-05-21')
INSERT INTO Collections VALUES(4,'wyh','2016-05-23')
INSERT INTO Collections VALUES(5,'wyh','2017-05-20')

INSERT [dbo].[MusicCategory] ([CategoryName], [CategoryImageUrl]) VALUES (N'流行/Pop', N'~\MusicShopFile\AlbumCategory\Category_01.gif')
INSERT [dbo].[MusicCategory] ([CategoryName], [CategoryImageUrl]) VALUES (N'古典音乐', N'~\MusicShopFile\AlbumCategory\Category_02.gif')
INSERT [dbo].[MusicCategory] ([CategoryName], [CategoryImageUrl]) VALUES (N'乡村民谣', N'~\MusicShopFile\AlbumCategory\Category_03.gif')
INSERT [dbo].[MusicCategory] ([CategoryName], [CategoryImageUrl]) VALUES (N'轻音乐', N'~\MusicShopFile\AlbumCategory\Category_04.gif')
INSERT [dbo].[MusicCategory] ([CategoryName], [CategoryImageUrl]) VALUES (N'舞曲', N'~\MusicShopFile\AlbumCategory\Category_05.gif')
INSERT [dbo].[MusicCategory] ([CategoryName], [CategoryImageUrl]) VALUES (N'军营歌曲', N'~\MusicShopFile\AlbumCategory\Category_06.gif')
INSERT [dbo].[MusicCategory] ([CategoryName], [CategoryImageUrl]) VALUES (N'影视乐曲', N'~\MusicShopFile\AlbumCategory\Category_07.gif')
INSERT [dbo].[MusicCategory] ([CategoryName], [CategoryImageUrl]) VALUES (N'民族音乐', N'~\MusicShopFile\AlbumCategory\Category_08.gif')
INSERT [dbo].[MusicCategory] ([CategoryName], [CategoryImageUrl]) VALUES (N'宗教音乐', N'~\MusicShopFile\AlbumCategory\Category_09.gif')
INSERT [dbo].[MusicCategory] ([CategoryName], [CategoryImageUrl]) VALUES (N'其他', N'~\MusicShopFile\AlbumCategory\Category_10.gif')

INSERT [dbo].[Orders] ([OrderDate], [UserName], [GoodsFee], [DeliverFee], [DeliverID], [AreaID], [PaymentID], [ReceiverName], [ReceiverAddress], [ReceiverPostCode], [ReceiverPhone], [ReceiverEmail], [OrderIsPayment], [OrderIsConsignment], [OrderIsConfirm], [OrderIsPigeonhole]) VALUES (CAST(0x9E5E0000 AS SmallDateTime), N'wt', CAST(655.00 AS Numeric(8, 2)), CAST(4.00 AS Numeric(8, 2)), 1, 1, 1, N'王良', N'北京市 海淀区', N'100098', N'82136688', N'wl@sina.com', 1, 1, 1, 1)
INSERT [dbo].[Orders] ([OrderDate], [UserName], [GoodsFee], [DeliverFee], [DeliverID], [AreaID], [PaymentID], [ReceiverName], [ReceiverAddress], [ReceiverPostCode], [ReceiverPhone], [ReceiverEmail], [OrderIsPayment], [OrderIsConsignment], [OrderIsConfirm], [OrderIsPigeonhole]) VALUES (CAST(0x9E880000 AS SmallDateTime), N'wyh', CAST(260.00 AS Numeric(8, 2)), CAST(4.00 AS Numeric(8, 2)), 1, 1, 1, N'李晓', N'北京市 朝阳区', N'100024', N'65758696', NULL, 1, 1, 1, 1)
INSERT [dbo].[Orders] ([OrderDate], [UserName], [GoodsFee], [DeliverFee], [DeliverID], [AreaID], [PaymentID], [ReceiverName], [ReceiverAddress], [ReceiverPostCode], [ReceiverPhone], [ReceiverEmail], [OrderIsPayment], [OrderIsConsignment], [OrderIsConfirm], [OrderIsPigeonhole]) VALUES (CAST(0x9C0F0000 AS SmallDateTime), N'wyh', CAST(260.00 AS Numeric(8, 2)), CAST(4.00 AS Numeric(8, 2)), 1, 1, 1, N'李晓', N'北京市 朝阳区', N'100024', N'65758696', NULL, 1, 1, 1, 1)
INSERT [dbo].[Orders] ([OrderDate], [UserName], [GoodsFee], [DeliverFee], [DeliverID], [AreaID], [PaymentID], [ReceiverName], [ReceiverAddress], [ReceiverPostCode], [ReceiverPhone], [ReceiverEmail], [OrderIsPayment], [OrderIsConsignment], [OrderIsConfirm], [OrderIsPigeonhole]) VALUES (CAST(0x9AF20000 AS SmallDateTime), N'sj', CAST(80.00 AS Numeric(8, 2)), CAST(4.00 AS Numeric(8, 2)), 1, 1, 2, N'宋键', N'北京市 朝阳区', N'100024', N'65778909', NULL, 1, 1, 1, 1)

INSERT [dbo].[Sales] ([OrderID], [AlbumID], [Quantity], [TotalPrice]) VALUES (1, 2, 3, CAST(255.00 AS Numeric(10, 2)))
INSERT [dbo].[Sales] ([OrderID], [AlbumID], [Quantity], [TotalPrice]) VALUES (1, 18, 5, CAST(400.00 AS Numeric(10, 2)))
INSERT [dbo].[Sales] ([OrderID], [AlbumID], [Quantity], [TotalPrice]) VALUES (2, 5, 1, CAST(100.00 AS Numeric(10, 2)))
INSERT [dbo].[Sales] ([OrderID], [AlbumID], [Quantity], [TotalPrice]) VALUES (2, 18, 2, CAST(160.00 AS Numeric(10, 2)))
INSERT [dbo].[Sales] ([OrderID], [AlbumID], [Quantity], [TotalPrice]) VALUES (3, 5, 1, CAST(100.00 AS Numeric(10, 2)))
INSERT [dbo].[Sales] ([OrderID], [AlbumID], [Quantity], [TotalPrice]) VALUES (3, 18, 2, CAST(160.00 AS Numeric(10, 2)))
INSERT [dbo].[Sales] ([OrderID], [AlbumID], [Quantity], [TotalPrice]) VALUES (4, 17, 1, CAST(80.00 AS Numeric(10, 2)))

